version: 2
jobs:
  deploy:
    docker:
      - image: ansible/ansible:ubuntu1604
        environment:
          ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      - run:
          name: Install Ansible
          command: pip install ansible
      - checkout
      - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
