version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ansible-playbook site.yml
            fi

