version: 2
jobs:
  deploy:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run:
          command:
            pip install ansible
      - run:
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
          command:
            ansible-playbook ansible/deploy.yml -i ansible/hosts.ini
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
