version: 2
jobs:
  deploy:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - run: ssh-keyscan -p 7002 dom.xperios.pl >> ~/.ssh/known_hosts
      - run: ssh ansible-dev@dom.xperios.pl -p 7002
      - run: exit
      - checkout
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
