version: 2
jobs:
  deploy:
    steps:
      - run: cat ~/.ssh/id_rsa.pub
      - run: ssh ansible-dev@dom.xperios.pl -p 7002
      - checkout
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
