version: 2
jobs:
  deploy:
    docker:
      - image: ansible/ansible:ubuntu1604
        environment:
          ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: pip install --upgrade pip && pip install ansible
      # Dependencies
      - checkout
      - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - deploy
