version: 2
jobs:
  deploy:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run:
          command:
            pip install ansible
      - run:
          command:
            curl ${ANSIBLE_HOSTS_CURL} >> ansible/hosts.yml
      - run:
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
          command:
            ansible-playbook -vvv ansible/deploy.yml -i ansible/hosts.yml
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
