# PREREQUISITE: ansible-dev user
#  sudo useradd ansible-dev -m -U
#  sudo passwd ansible-dev
#  sudo usermod -aG sudo ansible-dev

#- name: create system user
#  hosts: all
#  become: true
#
#  tasks:
#    - name: checking existing system user 
#      shell: grep -q "sys-dev" /etc/passwd
#      register: sys_user_checking
#      ignore_errors: true
#    - name: create system user 
#      user:
#        name: sys-dev
#      when:
#        sys_user_checking is failed
#
#- name: create app user
#  hosts: all
#  become: true
#
#  tasks:
#    - name: checking existing app user 
#      shell: grep -q "app-dev" /etc/passwd
#      register: app_user_checking
#      ignore_errors: true
#    - name: create app user 
#      user:
#        name: app-dev
#      when:
#        app_user_checking is failed

- name: consul deployment
  hosts: all
  become: true
  
  tasks:
    - name: Checking if consul is installed
      stat: path=/usr/local/bin/consul
      register: consul

    - name: Set-up Consul
      block:

        - name: Install binary
          block:

          - name: Download binary
            get_url:
              url: https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_arm.zip
              dest: ~/consul.zip

          - name: Unarchive binary
            unarchive:
              src: ~/consul.zip
              dest: /usr/local/bin
              remote_src: yes

        - name: Configure service
          block:
          - name: Creates directory
            file: path=/etc/consul.d state=directory

          - name: Copy config template
            template:
              src: consul/consul.config.json
              dest: /etc/consul.d/config.json

        - name: Configure systemd service
          block:

          - name: copy template
            template:
              src: consul/consul.service
              dest: /etc/systemd/system/consul.service

          - name: reload service
            systemd: daemon_reload=yes

          - name: enable service
            systemd:
              name: consul
              enabled: yes

          - name: Make sure a service is running
            systemd: state=started name=consul

#      when: not consul.stat.exists
    

